<?php
$lang["AppName"] = "Lokalise";
$lang["EnterUsername"] = "Enter your username";
$lang["EnterPassword"] = "Enter your password";
$lang["SignIn"] = "Sign In";
$lang["IncorrectPassword"] = "Incorrect password";
$lang["Cancel"] = "Cancel";
$lang["CreateAccount"] = "Create Account";
$lang["EnterEmail"] = "Enter your e-mail address";
$lang["AboutUs"] = "Our goal is to eliminate the hassle of localization by providing tools to automate, integrate, and better manage your translations. Lokalise is a better way for growth-minded businesses to expand their mobile apps, games, software or digital content into multiple languages.";
$lang["ContactUs"] = "Contact us";
$lang["Date"] = "Today is [%i].[%i].[%i]. and we are celebrating [%s].";
$lang["NameAge"] = "My name is [%1$s] [%2$s]. I am [%i] years old.";
$lang["Country"] = "I am from [%s].";
$lang["Hobby"] = "I like to [%s:hobby1], [%s:hobby2], [%s:hobby3] and [%s:hoby4].";
$lang["Family"] = "My mother is [%1$i] years old, my father is [%2$i] years old and my brother is [%3$i] years old.";
$lang["School"] = "I went to [%s] for [%i] years, then I went to [%s] for [%i] years and last school in which I studied was [%s] for [%i] years.";
$lang["Numbers"] = "The most popular number used is [%i:most_popular], [%i:least_popular] is the least popular number used.";
$lang["Information"] = "According to the caption on the bronze marker placed by the [%s:name] of the Daughters of the American Revolution on May 12, [%f], “College Hall (is) the oldest building in continuous use for Educational purposes west of the Rocky Mountains. Here were educated men and women who have won recognition throughout the world in all the learned professions.”";
$lang["Digits"] = "Number with first two digits after point is [%.2f], first three digits - [%.3f] and first seven digits - [%.7f]";
$lang["IceCream"] = "Chocolate ice cream cost [%1$.2f]$, vanilla ice cream costs [%2$.2f]$ and peppermint ice cream costs [%3$.2f]$.";
$lang["Score"] = "[%s:student] got only [%.2f:student_name] points in test, so [%s:student] didn't pass the test. [%.2f:student_name] was the worst score on the test.";
$lang["EmptyKey"] = "[VOID]";
$lang["True"] = "[TRUE]";
$lang["False"] = "[FALSE]";
$lang["Weather"] = "Today the weather is good. We are expecting [%s].";
$lang["EmptyPlaceholder"] = "[%]";
$lang["files"] = "{files, plural, one {{count} file.} other {{count} files.}}";
$lang["books"] = "{score, plural, one {One book} other {{count} books}}";
$lang["cats"] = "{cats, plural, one {{count} cat.} other {}}";
$lang["friends"] = "{friends, plural, one {} other {{count} friends.}}";
$lang["empty"] = "{empty, plural, one {} other {}}";
$lang["amount"] = "{amount, plural, one {1} other {1000}}";
$lang["long"] = "{long, plural, one {View fine me gone this name an rank. Compact greater and demands mrs the parlors. Park be fine easy am size away. Him and fine bred knew. At of hardly sister favour. As society explain country raising weather of. Sentiments nor everything off out uncommonly partiality bed.} other {It real sent your at. Amounted all shy set why followed declared. Repeated of endeavor mr position kindness offering ignorant so up. Simplicity are melancholy preference considered saw companions. Disposal on outweigh do speedily in on. Him ham although thoughts entirely drawings. Acceptance unreserved old admiration projection nay yet him. Lasted am so before on esteem vanity oh.}}";
$lang["spec_characters"] = "{spec_characters, plural, one {The most used special character is a dot - .} other {There are a lot of special characters that can be used, for example, !, @, £, $, %, ^, &, *, (, )}}";
$lang["float_numbers"] = "{float_numbers, plural, one {0.31} other {-0.1}}";
$lang["score"] = "{score, plural, one {One point} other {{{totalScore}} points}}";
$lang["money"] = "{money, plural, =1 {I have 1$} other {I don't have any money}}";
$lang["people"] = "{score, plural, one {One person} other {{count} people}}";
$lang["plane"] = "{plane, plural, =1 {} other {There are many planes}}";
$lang["window"] = "{window, plural, =1 {There is one window} other {}}";
$lang["empty_numeric"] = "{empty_numeric, plural, =1 {} other {}}";
$lang["numbers"] = "{numbers, plural, =1 {1} other {0}}";
$lang["long_numeric"] = "{long_numeric, plural, =1 {You disposal strongly quitting his endeavor two settling him. Manners ham him hearted hundred expense. Get open game him what hour more part. Adapted as smiling of females oh me journey exposed concern. Met come add cold calm rose mile what. Tiled manor court at built by place fanny. Discretion at be an so decisively especially. Exeter itself object matter if on mr in. } other {No in he real went find mr. Wandered or strictly raillery stanhill as. Jennings appetite disposed me an at subjects an. To no indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week. Almost do am or limits hearts. Resolve parties but why she shewing. She sang know now how nay cold real case.}}";
$lang["spec_characters_numeric"] = "{spec_characters_numeric, plural, =1 {The most used special character is a dot - .} other {There are a lot of special characters that can be used, for example, !, @, £, $, %, ^, &, *, (, )}}";
$lang["float_numeric"] = "{float_numeric, plural, =1 {-0.34} other {1.43}}";
$lang["points"] = "{points, plural, =1 {One point} other {{{total}} points}}";
$lang["family"] = "{family, plural, one {Person has [%i] family member.} other {Person has [%i] family members.}}";
$lang["family_names"] = "{family_names, plural, one {The family member is [%1$s] [%2$s], [%3$s] name is [%4$s].} other {The family members are [%1$s], their names are [%2$s].}}";
$lang["celebrate"] = "{celebrate, plural, one {My birthday is on [%1$i].[%2$i].[%3$i]. and I celebrate it on the same day.} other {My birthday is on [%1$i].[%2$i].[%3$i]. and I celebrate it on [%4$i].[%5$i].[%6$i].}}";
$lang["hobby"] = "{hobby, plural, one {I like to [%s:hobby].} other {I like to [%s:hobby1], [%s:hobby2], [%s:hobby3] and [%s:hoby4].}}";
$lang["true_or_false"] = "{true_or_false, plural, one {[TRUE]} other {[FALSE]}}";
$lang["empty_placeholder"] = "{empty_placeholder, plural, =1 {[VOID]} other {[%]}}";
$lang["text"] = "{text, plural, =1 {[%s]} other {[%1$s] [%2$s] [%3$s] [%4$s]}}";
$lang["popular_name"] = "{popular_name, plural, =1 {Most popular name is [%s:name].} other {Two most popular names are [%s:name1] and [%s:name2].}}";
$lang["digits"] = "{digits, plural, =1 {Number with first two digits after point is [%.2f].} other {Number with first two digits after point is [%.2f], first three digits - [%.3f] and first seven digits - [%.7f]}}";
